name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test on destination ${{ matrix.destination }}
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=macOS", "platform=iOS Simulator,name=iPhone 8"]
    steps:
      - uses: actions/checkout@v2
      - name: xcodebuild test ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild test -scheme Flexer -destination "${{ matrix.destination }}" | xcpretty